version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker-publish: circleci/docker-publish@0.1.3
workflows:

  # This workflow will be run on all branches but master (to test)
  build_without_publishing_job:
    jobs:
      - docker-publish/publish:
          image: singularityhub/sif
          deploy: false
          filters:
            branches:
              ignore: master

  docker_with_lifecycle:
    jobs:
      - docker-publish/publish:
          image: singularityhub/sif
          deploy: false
          filters:
            branches:
              ignore: master
          after_build:
            - run:
                name: Preview Docker Tag for Build
                command: |
                   DOCKER_TAG=$(docker run singularityhub/sif --version)
                   echo "Version for Docker tag is ${DOCKER_TAG}"

  # This workflow will deploy images on merge to master only
  build_and_publish_docker_images:
    jobs:
      - docker-publish/publish:
          image: pydicom/dicom-header-cleaner
          dockerfile: header/Dockerfile
          path: header
          filters:
            branches:
              only: master
      - docker-publish/publish:
          image: pydicom/dicom-header-cleaner
          tag: latest
          dockerfile: header/Dockerfile
          path: header
          filters:
            branches:
              only: master
