#----
# Site

title: sif python
url: "https://singularityhub.github.io/sif"
baseurl: "/sif"
show_full_navigation: false

logo: assets/img/logo.png
description: Documentation for SIF Python
author:
  name:
  email: vsochat@stanford.edu
  twitter: # twitter username without the @ symbol
social:
  name: vsoch
  links:
    - https://github.com/singularityhub

# The current hosting location of the docs
repo: singularityhub/sif
reponame: sif

# The current Docker container
docker: singularityhub/sif

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# ---------
# ChangeLog

types:
  - minor
  - major
